### ISSUE TITLE
Empty <title> tag on production

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint-demo#129]
I found `<title>` tag is empty on <https://stylelint.io/demo/>.

![image](https://user-images.githubusercontent.com/473530/47784900-6c5aab80-dd4a-11e8-9bef-8b08611b817c.png)

I think this is a bug, but I can't find the way to fix it. 😢

**Comment by jeddy3** [comment]
This is likely an issue with the website, rather than the demo itself.

It should have the title "Demo" because [of these lines](https://github.com/stylelint/stylelint.io/blob/master/scripts/copy-stylelint-docs.js#L68-L74) but it doesn't seem to be working.

**Comment by ybiquitous** [comment]
Oh, I see! I try to see more. 💪

**Comment by ybiquitous** [comment]
Perhaps a first heading (e.g. `# Developer guide`) in a `.md` file may become its title...?

https://github.com/stylelint/stylelint/blob/5fd5905e9614da4725eb2e9c16351e4aa76fd1d4/docs/developer-guide.md

**Comment by jeddy3** [comment]
I think it's because the demo uses the [`DemoPage` layout](https://github.com/stylelint/stylelint.io/blob/master/src/layouts/DemoPage/index.js) but that doesn't, unlike the [`Page` layout](https://github.com/stylelint/stylelint.io/blob/master/src/layouts/Page/index.js), use `react-helmet` to set the `<title>` from the frontmatter. 

Maybe the `DemoPage` layout can be more like the [`RulePage` layout](https://github.com/stylelint/stylelint.io/blob/master/src/layouts/RulePage/index.js) and make use of the `Page` layout. Having said that, all this is related to the engine and can be resolved by moving https://github.com/stylelint/stylelint.io/issues/58 forward.

Eitherway, I think we can close this issue here and it's not related to the stylelint-demo code itself.

**Comment by jeddy3** [comment]
Snap! You put your PR up just as I posted. :)

**Comment by ybiquitous** [comment]
Yeah, I reached the same reason! I opened the PR right now! 😄 

https://github.com/stylelint/stylelint.io/pull/62

**Comment by ybiquitous** [comment]
> Having said that, all this is related to the engine and can be resolved by moving [stylelint/stylelint.io#58](https://github.com/stylelint/stylelint.io/issues/58) forward.

I agree with moving the engine. 👍 

It was hard for me to find [the current engine's documentation](https://phenomic.io/en/packages/preset-react-app/docs/getting-started/04/#the-front-matter)... 😓

**Comment by ybiquitous** [comment]
New version was deployed.

![image](https://user-images.githubusercontent.com/473530/47791892-168ffe80-dd5e-11e8-8818-f39a55e753a5.png)
